### ISSUE TITLE
[Bug] Enderchests and Anvils refill health rather than get destroyed

### ISSUE THREAD

**Issue by Andell4301** [CactusBurrito/ObsidianRaider#8]
I have the following lines in my config:
```yml
Damageable Block Health:
  obsidian: 8.0
  ender_chest: 8.0
  anvil: 5.0
```
While obsidian works fine, upon reaching 0%, anvils and ender_chests refill themselves to 100% health and never actually get destroyed.
I haven't tested with any blocks besides these three.
